// 검색·완료 렌더 연막검사용 firebase 메모리 스텁(3.2-01) — src 가 firebase.js 에서 가져오는 이름 전부를 무해한 함수로. 실제 쓰기 없음.
//   fbCompleteContainer·fbCompleteContainersAtomic·fbReassignContainerPosition 만 window.__calls 에 남긴다.
//   ⚠ 새 이름이 firebase.js 에 생기면 tools/gen_fb_stub.py 로 다시 만든다(빌드가 «is not exported» 로 막는다).
export const STORAGE_BAY = '__STG__';
export const app = {};
export const db = {};
export const fbAddClaudeMemo = async () => true;
export const fbAddExtraContainer = async () => true;
export const fbAddFoodSpot = async () => true;
export const fbAddPendingDamage = async () => true;
export const fbAddPhotoReport = async () => true;
export const fbAddReportsAt = async () => true;
export const fbAddShipStats = async () => true;
export const fbAddShipVoyage = async () => true;
export const fbAddStaff = async () => true;
export const fbAddSwapFix = async () => true;
export const fbAddWorkReport = async () => true;
export const fbApplyTermWork = async () => true;
export const fbArchiveVoyageBeforeDelete = async () => true;
export const fbAssignDeckSlot = async () => true;
export const fbBackupAll = async () => true;
export const fbBatchMoveToStorage = async () => true;
export const fbBatchSaveShipBayDict = async () => true;
export const fbBulkCancelComplete = async () => true;
export const fbCancelComplete = async () => true;
export const fbCancelLuggConfirm = async () => true;
export const fbCleanupActivityLog = async () => true;
export const fbCleanupArchive = async () => true;
export const fbClearActualPosition = async () => true;
export const fbClearAllActiveWork = async () => true;
export const fbClearAllReports = async () => true;
export const fbClearAllReportsAllVoyages = async () => true;
export const fbClearBroadcast = async () => true;
export const fbClearFeedback = async () => true;
export const fbCommentFoodSpot = async () => true;
export const fbCommitPlan = async () => true;
export const fbCompleteContainer = async (vk, mode, cn, by, flag, note, equip) => { window.__calls.push({ fn: 'complete', vk, mode, cn, by, equip }); return true; };
export const fbCompleteContainersAtomic = async (vk, mode, cns, by, equip) => { window.__calls.push({ fn: 'completeAtomic', vk, mode, cns, by, equip }); return true; };
export const fbCreateVoyage = async () => true;
export const fbDeleteClaudeMemo = async () => true;
export const fbDeleteFeedback = async () => true;
export const fbDeleteFoodSpot = async () => true;
export const fbDeleteISO403Photo = async () => true;
export const fbDeleteInspector = async () => true;
export const fbDeletePendingDamage = async () => true;
export const fbDeletePushToken = async () => true;
export const fbDeleteReport = async () => true;
export const fbDeleteSection = async () => true;
export const fbDeleteShipBayDict = async () => true;
export const fbDeleteStaff = async () => true;
export const fbDeleteVoyage = async () => true;
export const fbDeleteWorkReport = async () => true;
export const fbFoodListen = async () => true;
export const fbGetActivityDays = async () => true;
export const fbGetAdminGuard = async () => true;
export const fbGetArchiveVoyage = async () => true;
export const fbGetClaudeMemos = async () => true;
export const fbGetDamagePhoto = async () => true;
export const fbGetEdiRaw = async () => true;
export const fbGetPendingDamage = async () => true;
export const fbGetShipIntro = async () => true;
export const fbGetShipSeqPref = async () => true;
export const fbGetShipStructure = async () => true;
export const fbGetSimple = async () => null;
export const fbHoldContainers = async () => true;
export const fbIsOnline = async () => true;
export const fbListArchive = async () => true;
export const fbListTallyPending = async () => true;
export const fbLogMirMiss = async () => true;
export const fbLogoutInspector = async () => true;
export const fbMarkBroadcastRead = async () => true;
export const fbMarkDeletedStaff = async () => true;
export const fbPromotePendingDamage = async () => true;
export const fbRateFoodSpot = async () => true;
export const fbReassignContainerPosition = async (vk, mode, cn, b, r, t, by, opts) => { window.__calls.push({ fn: 'reassign', cn, to: `${b}-${r}-${t}`, opts: opts || null }); return { ok: true }; };
export const fbReconnect = async () => true;
export const fbReleaseHold = async () => true;
export const fbRemoveAdminDevice = async () => true;
export const fbRemoveExtraContainer = async () => true;
export const fbRemoveSwapFix = async () => true;
export const fbReplacePortMisBatch = async () => true;
export const fbReportWrongAnswer = async () => true;
export const fbRequestProcessNow = async () => true;
export const fbResolveFeedback = async () => true;
export const fbRestorePlanFromEdi = async () => true;
export const fbRestoreVoyageFromArchive = async () => true;
export const fbSaveEdiContainers = async () => true;
export const fbSaveEdiRaw = async () => true;
export const fbSaveISO403Photo = async () => true;
export const fbSaveListRecords = async () => true;
export const fbSavePierCoord = async () => true;
export const fbSavePlanDraft = async () => true;
export const fbSavePortMisBatch = async () => true;
export const fbSavePushToken = async () => true;
export const fbSaveSectionData = async () => true;
export const fbSaveShipBayDict = async () => true;
export const fbSaveShipIntro = async () => true;
export const fbSaveShipStructure = async () => true;
export const fbSaveXrayList = async () => true;
export const fbSeedFoodSpotsOnce = async () => true;
export const fbSetActualPosition = async () => true;
export const fbSetBroadcast = async () => true;
export const fbSetDevAccess = async () => true;
export const fbSetEmptySeal = async () => true;
export const fbSetInspector = async () => true;
export const fbSetInspectorActivity = async () => true;
export const fbSetLuggConfirm = async () => true;
export const fbSetMatrixEditors = async () => true;
export const fbSetReeferTempBulk = async () => true;
export const fbSetShipSeqPref = async () => true;
export const fbSetSimple = async () => true;
export const fbSetStaffRole = async () => true;
export const fbSetStowagePlan = async () => true;
export const fbSetVoyageGangs = async () => true;
export const fbSetVoyageSeqMode = async () => true;
export const fbSetVoyageWorkStart = async () => true;
export const fbSetXraySeal = async () => true;
export const fbSnoozeHold = async () => true;
export const fbSubscribeAllReports = async () => true;
export const fbSubscribeBroadcast = async () => true;
export const fbSubscribeBroadcastReads = async () => true;
export const fbSubscribeConnection = async () => true;
export const fbSubscribeDeletedStaff = async () => true;
export const fbSubscribeDevAccess = async () => true;
export const fbSubscribeFeedback = async () => true;
export const fbSubscribeHeartbeat = async () => true;
export const fbSubscribeInspectors = async () => true;
export const fbSubscribeLaneInfo = async () => true;
export const fbSubscribeLaneRoutes = async () => true;
export const fbSubscribeMatrixEditors = async () => true;
export const fbSubscribeMirLexicon = async () => true;
export const fbSubscribePierCoords = async () => true;
export const fbSubscribePilotForecast = async () => true;
export const fbSubscribePortMis = async () => true;
export const fbSubscribeProcessDone = async () => true;
export const fbSubscribeShipBayDict = async () => true;
export const fbSubscribeShipLibrary = async () => true;
export const fbSubscribeStaffList = async () => true;
export const fbSubscribeTerminalWork = async () => true;
export const fbSubscribeVoyages = async () => true;
export const fbSubscribeWorkReports = async () => true;
export const fbToggleXray = async () => true;
export const fbUnassignContainer = async () => true;
export const fbUnmarkDeletedStaff = async () => true;
export const fbUpdateAdminGuard = async () => true;
export const fbUpdateRecordField = async () => true;
export const fbUpdateRecordSeal = async () => true;
export const fbUpdateVoyageInfo = async () => true;
export const fbWriteMirLexicon = async () => true;
function resolveSeqMode(info) {
  if (!info) return null;
  const m = String(info.seqMode || '').trim();
  if (SEQ_MODES.includes(m)) return m;
  const v = info.seqFull;
  if (v === true || v === 'true' || v === 1) return 'fullOnlySeq';
  if (v === false || v === 'false' || v === 0) return 'allActual';
  return null;
}
export { resolveSeqMode };
function tallyVoyagesByShip(voyages) {
  const byShip = {};
  for (const [key, v] of Object.entries(voyages || {})) {
    const info = v.info || {};
    const vsl = (info.vsl || key.split('_')[0] || '(선박명 미상)').toUpperCase();
    // V8.09-12: vsl 자리에 항만코드(CNYNT=옌타이 등)가 잘못 저장된 항차는 별도 선박으로
    //   그룹핑하지 않는다. OBWH 항차의 목적항 코드가 vsl로 새어 수석대시보드에 OBWH와
    //   중복 카드(CNYNT)가 생기던 문제. 항만코드 그룹은 표시에서 제외(데이터는 보존).
    if (isPortCode(vsl)) continue;
    if (!byShip[vsl]) byShip[vsl] = { vsl, discharge: 0, loading: 0, voyageKeys: [] };
    byShip[vsl].discharge += _ptkCountOfSection(v.discharge, 'discharge');
    byShip[vsl].loading += _ptkCountOfSection(v.loading, 'loading');
    byShip[vsl].voyageKeys.push(key);
  }
  return Object.values(byShip).sort((a, b) => (b.discharge + b.loading) - (a.discharge + a.loading));
}
export { tallyVoyagesByShip };
